# Generated by Django 3.1 on 2020-09-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func_view_under_cls_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='my_Course',
        ),
    ]
