# Generated by Django 3.1 on 2020-09-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func_view_under_cls_view', '0002_auto_20200903_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_Course',
            new_name='Course',
        ),
    ]
