# Generated by Django 3.1 on 2020-09-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_based_work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articale',
            new_name='Article',
        ),
    ]
