# Generated by Django 3.1 on 2020-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_based_work', '0002_auto_20200902_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=120),
        ),
    ]
