# Generated by Django 3.1 on 2020-09-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testtable',
        ),
    ]
